# Site settings
title: Filip Ginter
subtitle: home
email: ginter@cs.utu.fi
description: homepage 
baseurl: "/"
url: "https://fginter.github.io" # the base hostname & protocol for your site
author:
street_address: Department of IT
city: University of Turku
state: 
zip_code: 20014
country: Finland
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/fginter
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/filip-ginter-3519b44
pinterest_url:
slack_url:
twitter_url: https://twitter.com/FilipGinterFIN

# Build settings
markdown: kramdown
